# 기본 환경 선택
spring:
  # Database
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/switty
    username: switty
    password: switty

  # JPA properties
  jpa:
    # database: oracle
    # database: mysql
    # database: postgresql
#    database: maria
    hibernate:
      use-new-id-generator-mappings: true
      # 하이버네이트에서 스키마 구조를 생성해줌
      # 추후에 변경해야함
      ddl-auto: update
      #ddl-auto: none
    open-in-view: false
    generate-ddl: false
    properties:
      hibernate:
        show-sql: true
        format_sql: true
        globally_quoted_identifiers: false
        jdbc:
          lob:
            non_contextual_creation: true
      jdbc:
        time_zone: UTC
        temp:
          use_jdbc_metadata_defaults: false


# mybatis config
  mybatis:
    mapper-locations=mappers/*.xml

